### ISSUE TITLE
Style developer results page

### ISSUE THREAD

**Issue by TimvdLippe** [Tindev/Tindev-site#13]
When a user queries the system, the page should show one developer at a time, nicely styled with useful information. This is already implemented with the data, but lacks the styling atm.

**Comment by GijsWeterings** [comment]
This is either /classify or /results, but as I don't know which one I'm deferring this to tomorrow evening

**Comment by TimvdLippe** [comment]
@GijsWeterings this is /classify

**Comment by TimvdLippe** [comment]
Okay, my bad. It is actually /results. Editing the title 😭
