### ISSUE TITLE
When a user fills in the information on the homepage, the query should be executed

### ISSUE THREAD

**Issue by TimvdLippe** [Tindev/Tindev-site#14]
I recall @GijsWeterings having some code lying around, but it has not been pushed. Therefore, we have to hook up the filled in data to a functional elasticsearch query and consequently show the data in the frontend.

**Comment by GijsWeterings** [comment]
@TimvdLippe pushed the code this afternoon, did you manage to merge it?

**Comment by TimvdLippe** [comment]
Yes it did. https://github.com/Tindev/Tindev-site/commit/7dd154dff4efdc166fe3c93fa7f53fd6b166e96a
